config/routes.rb
Rails.application.routes.draw do
 
  resources :campaigns do
    resources :discussion_topics
    resources :comments
  end
  resources :campaigns
  root 'campaigns#index'
  devise_for :users, controllers: { sessions: "sessions" }

end

app/models/discussion_topic.rb
class DiscussionTopic < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
end

app/controllers/discussion_topics_controller.rb
class DiscussionTopicsController < ApplicationController
  before_action :set_discussion_topic, only: %i[ show edit update destroy ]

  # GET /discussion_topics or /discussion_topics.json
  def index
    @discussion_topics = DiscussionTopic.all
  end

  # GET /discussion_topics/1 or /discussion_topics/1.json
  def show
  end

  # GET /discussion_topics/new
  def new
    @campaign = Campaign.find_by(params[:campaign_id])
    @discussion_topic = @campaign.discussion_topics.new
  end

  # GET /discussion_topics/1/edit
  def edit
  end

  # POST /discussion_topics or /discussion_topics.json
  def create
    @campaign = Campaign.find_by(params[:campaign_id])
    @discussion_topic = @campaign.discussion_topics.create(discussion_topic_params)
  
    respond_to do |format|
     # if @discussion_topic.save
        format.html { redirect_to campaign_path(@campaign), notice: "Discussion topic was successfully created." }
        format.json { render :show, status: :created, location: @discussion_topic }
     # else
       # format.html { render :new, status: :unprocessable_entity }
       # format.json { render json: @discussion_topic.errors, status: :unprocessable_entity }
      #end
    end
  end

  # PATCH/PUT /discussion_topics/1 or /discussion_topics/1.json
  def update
    respond_to do |format|
      if @discussion_topic.update(discussion_topic_params)
        format.html { redirect_to discussion_topic_url(@discussion_topic), notice: "Discussion topic was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion_topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussion_topics/1 or /discussion_topics/1.json
  def destroy
    @discussion_topic.destroy

    respond_to do |format|
      format.html { redirect_to discussion_topics_url, notice: "Discussion topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion_topic
      @discussion_topic = DiscussionTopic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discussion_topic_params
      params.require(:discussion_topic).permit(:title, :user_id, :campaign_id)
    end
end

app/helpers/discussion_topics_helper.rb
module DiscussionTopicsHelper
end

app/views/discussion_topics/_discussion_topic.html.erb
<div id="<%= dom_id discussion_topic %>">
  <p>
    <strong>Title:</strong>
    <%= discussion_topic.title %>
  </p>

</div>

app/views/discussion_topics/_form.html.erb
<%= form_with model: [@campaign, @campaign.discussion_topics.build] do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/discussion_topics/edit.html.erb
<h1>Editing discussion topic</h1>

<%= render "form", discussion_topic: @discussion_topic %>

<br>

<div>
  <%= link_to "Show this discussion topic", @discussion_topic %> |
  <%= link_to "Back to discussion topics", discussion_topics_path %>
</div>

app/views/discussion_topics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Discussion topics</h1>

<div id="discussion_topics">
  <% @discussion_topics.each do |discussion_topic| %>
    <%= render discussion_topic %>
    <p>
      <%= link_to "Show this discussion topic", discussion_topic %>
    </p>
  <% end %>
</div>

<%= link_to "New discussion topic", new_campaign_discussion_topic_path(@campaign) %>

app/views/discussion_topics/new.html.erb
<h1>New discussion topic</h1>

<%= render "form", discussion_topic: @discussion_topic %>

<br>

<div>
  <%#= link_to "Back to discussion topics", discussion_topics_path %>
</div>

app/views/discussion_topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @discussion_topic %>

<div>
  <%= link_to "Edit this discussion topic", edit_discussion_topic_path(@discussion_topic) %> |
  <%= link_to "Back to discussion topics", discussion_topics_path %>

  <%= button_to "Destroy this discussion topic", @discussion_topic, method: :delete %>
</div>