config/routes.rb
Rails.application.routes.draw do
 
  resources :campaigns do
    resources :discussion_topics
    resources :comments
  end
  resources :campaigns
  root 'campaigns#index'
  devise_for :users, controllers: { sessions: "sessions" }

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :comments
  belongs_to :user
  has_many :discussion_topics
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = current_user.campaigns
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = current_user.campaigns.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = current_user.campaigns.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:title, :purpose, :estimated_duration)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p>
    <strong>Title:</strong>
    <%= campaign.title %>
  </p>

  <p>
    <strong>Purpose:</strong>
    <%= campaign.purpose %>
  </p>

  <p>
    <strong>Estimated duration:</strong>
    <%= campaign.estimated_duration %>
  </p>

</div>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :purpose, style: "display: block" %>
    <%= form.text_field :purpose %>
  </div>

  <div>
    <%= form.label :estimated_duration, style: "display: block" %>
    <%= form.radio_button :estimated_duration, "within 1 week" %>
    <%= form.label :estimated_duration, "within 1 week" %>
    <%= form.radio_button :estimated_duration, "within 1 month" %>
    <%= form.label :estimated_duration, "within 1 month" %>
    <%= form.radio_button :estimated_duration, "within 3 month" %>
    <%= form.label :estimated_duration, "within 3 month" %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Campaigns</h1>

<div id="campaigns">
  <% @campaigns.each do |campaign| %>
    <%= render campaign %>
    <p>
      <%= link_to "Show this campaign", campaign %>
    </p>
  <% end %>
</div>

<%= link_to "New campaign", new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campaign %>

<div>
  <%= link_to "Edit this campaign", edit_campaign_path(@campaign) %> |
  <%= link_to "Back to campaigns", campaigns_path %>

  <%= button_to "Destroy this campaign", @campaign, method: :delete %>
  <%#= link_to "New comment", new_campaign_comment_path(@campaign) %>
</div>


<%= render @campaign.comments %>
<%= render @campaign.discussion_topics %>

<%= render 'comments/form'%>
<%= render 'discussion_topics/form' %>